CREATE DATABASE LOJA_DE_PECAS

CREATE TABLE FORNECEDORES(
CODIGO_INTERNO INTEGER(15) NOT NULL PRIMARY KEY,
NOME VARCHAR(200) NOT NULL,
RUA VARCHAR(50) NOT NULL,
BAIRRO VARCHAR(50) NOT NULL,
CIDADE VARCHAR(50) NOT NULL
);

CREATE TABLE INTERNACIONAIS(
CODIGO_INTERNO INTEGER(15) NOT NULL,
FOREIGN KEY (CODIGO_INTERNO) REFERENCES FORNECEDORES (CODIGO_INTERNO),
TRANSPORTE VARCHAR(40) NOT NULL,
PAIS VARCHAR(40) NOT NULL,
MOEDA VARCHAR(30) NOT NULL
);

CREATE TABLE NACIONAIS(
CNPJ INTEGER(15) NOT NULL PRIMARY KEY,
CODIGO_INTERNO INTEGER(15) NOT NULL,
FOREIGN KEY (CODIGO_INTERNO) REFERENCES FORNECEDORES (CODIGO_INTERNO),
CIDADE VARCHAR(50) NOT NULL
);

CREATE TABLE TELEFONE_FORNECEDORES(
CODIGO_TELEFONE INTEGER(10) NOT NULL PRIMARY KEY,
CODIGO_INTERNO INTEGER(15) NOT NULL,
FOREIGN KEY (CODIGO_INTERNO) REFERENCES FORNECEDORES (CODIGO_INTERNO),
TELEFONE_FORNECEDORES VARCHAR(30) NOT NULL
);

CREATE TABLE MERCADORIA(
CODIGO INTEGER(20) NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(50) NOT NULL,
PRECO DECIMAL(5,2) NOT NULL,
QUANTIDADE_DE_ESTOQUE INTEGER(5) NOT NULL
);

CREATE TABLE MERC_FORNECIDAS(
CODIGO INTEGER(20) NOT NULL,
FOREIGN KEY (CODIGO) REFERENCES MERCADORIA (CODIGO),
CODIGO_INTERNO INTEGER(15) NOT NULL,
FOREIGN KEY (CODIGO_INTERNO) REFERENCES FORNECEDORES (CODIGO_INTERNO)
);

CREATE TABLE CLIENTE(
CPF INT(15) NOT NULL PRIMARY KEY,
NOME VARCHAR(200) NOT NULL,
RUA VARCHAR(50) NOT NULL,
BAIRRO VARCHAR(50) NOT NULL,
CIDADE VARCHAR(50) NOT NULL,
RG INTEGER(20) NOT NULL
);

CREATE TABLE PEDIDO(
NOTA_FISCAL INTEGER(15) NOT NULL PRIMARY KEY,
PRECO_TOTAL DECIMAL(5,2) NOT NULL,
DATA_PEDIDO DATE NOT NULL,
CPF INT(15) NOT NULL,
FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF)
);

CREATE TABLE ITENS_PEDIDOS(
NOTA_FISCAL INTEGER(15) NOT NULL,
FOREIGN KEY (NOTA_FISCAL) REFERENCES PEDIDO (NOTA_FISCAL),
CODIGO INTEGER(20) NOT NULL,
FOREIGN KEY (CODIGO) REFERENCES MERCADORIA (CODIGO),
QUANTIDADE INTEGER(5) NOT NULL,
CODIGO_ITEM INTEGER(10) NOT NULL
);

CREATE TABLE EMAIL_CLIENTE(
CODIGO_EMAIL INTEGER(10) NOT NULL PRIMARY KEY,
EMAIL VARCHAR(30) NOT NULL,
CPF INT(15) NOT NULL,
FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF)
);