CREATE DATABASE LOCADORA_DE_AUTOS

CREATE TABLE CATEGORIA(
CODIGO_CATEGORIA VARCHAR(50) NOT NULL PRIMARY KEY,
DESCRIÇÃO VARCHAR(200) NOT NULL,
PRECO_DIARIA INTEGER(10) NOT NULL
);

CREATE TABLE CARRO(
NUMERO_CHASSI INTEGER(17) NOT NULL PRIMARY KEY,
CODIGO_CATEGORIA VARCHAR(50) NOT NULL,
FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA (CODIGO_CATEGORIA),
PLACA VARCHAR(8) NOT NULL,
MARCA VARCHAR(20) NOT NULL,
ANO INTEGER(5) NOT NULL,
COR VARCHAR(10) NOT NULL
);

CREATE TABLE OFICINA(
CNPJ INTEGER(14) NOT NULL PRIMARY KEY,
NOME VARCHAR(25) NOT NULL,
EMAIL VARCHAR(25) NOT NULL,
TELEFONE INTEGER(10) NOT NULL,
RUA VARCHAR(100) NOT NULL,
NUMERO INTEGER(5) NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(20) NOT NULL
);

CREATE TABLE MANUTENÇÃO(
CODIGO_MANUTENÇÃO VARCHAR(50) NOT NULL PRIMARY KEY,
CNPJ INTEGER(14) NOT NULL,
FOREIGN KEY (CNPJ) REFERENCES OFICINA (CNPJ),
NUMERO_CHASSI INTEGER(17) NOT NULL,
FOREIGN KEY (NUMERO_CHASSI) REFERENCES CARRO (NUMERO_CHASSI),
DIA DATE NOT NULL,
DESCRIÇÃO VARCHAR(200) NOT NULL,
VALOR INTEGER(5) NOT NULL
);

CREATE TABLE USUARIO(
CNH INTEGER(10) NOT NULL PRIMARY KEY,
NOME VARCHAR(25) NOT NULL,
RG INTEGER(10) NOT NULL,
EMAIL VARCHAR(25) NOT NULL,
IDADE INTEGER(3) NOT NULL,
TELEFONE INTEGER(10) NOT NULL,
RUA VARCHAR(100) NOT NULL,
NUMERO VARCHAR(5) NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(20) NOT NULL
);

CREATE TABLE ALOCA(
NUMERO_CHASSI INTEGER(17) NOT NULL,
FOREIGN KEY (NUMERO_CHASSI) REFERENCES CARRO (NUMERO_CHASSI),
CNH INTEGER(10) NOT NULL,
FOREIGN KEY (CNH) REFERENCES USUARIO (CNH),
DIA DATE NOT NULL,
HORA INTEGER(4) NOT NULL
);