DROP DATABASE RECURSOS_HUMANOS;
CREATE DATABASE RECURSOS_HUMANOS;

CREATE TABLE FUNCIONARIO(
	ID_FUNCIONARIO INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50),
	ENDERECO VARCHAR(100) NULL,
	CIDADE VARCHAR(50) NULL,
	ESTADO CHAR(2) NULL,
	EMAIL VARCHAR(50) NULL UNIQUE,
	DATA_DE_NASCIMENTO DATE NULL;

ALTER TABLE FUNCIONARIO ADD SALARIO DECIMAL(7,2) NULL, ADD CARGOS VARCHAR(2) NULL;

ALTER TABLE FUNCIONARIO DROP COLUMN CARGOS;

ALTER TABLE FUNCIONARIO ADD CARGO VARCHAR(20), ADD ATIVO BIT;