CREATE DATABASE VICTOR_THEODORO;

CREATE TABLE ALUNO(
CODIGO_MATRICULA VARCHAR(100) NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
DATA_MATRICULA DATE NOT NULL,
TELEFONE INTEGER(20) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
ALTURA DECIMAL(10) NOT NULL,
PESO INTEGER(10) NOT NULL,
RUA VARCHAR(60) NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(30) NOT NULL
);

CREATE TABLE INSTRUTOR(
RG INTEGER(20) NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
TELEFONE INTEGER(20) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
TITULAÇÃO VARCHAR(20) NOT NULL
);

CREATE TABLE ALUNO_MONITOR(
CODIGO_MATRICULA VARCHAR(100) NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL
);

CREATE TABLE TURMA(
CODIGO_TURMA VARCHAR(100) NOT NULL PRIMARY KEY,
CODIGO_MATRICULA VARCHAR(100) NOT NULL,
FOREIGN KEY (CODIGO_MATRICULA) REFERENCES ALUNO (CODIGO_MATRICULA),
RG INTEGER(20) NOT NULL,
FOREIGN KEY (RG) REFERENCES INSTRUTOR (RG),
NUMERO_ALUNOS INTEGER(10) NOT NULL,
TIPO_ATIVIDADE VARCHAR(50) NOT NULL,
HORARIO_AULA INTEGER(10) NOT NULL,
DATA_INICIAL DATE NOT NULL,
DATA_FINAL DATE NOT NULL
);

CREATE TABLE MATRICULA(
CODIGO_TURMA VARCHAR(100) NOT NULL,
FOREIGN KEY (CODIGO_TURMA) REFERENCES TURMA (CODIGO_TURMA),
CODIGO_MATRICULA VARCHAR(100) NOT NULL,
FOREIGN KEY (CODIGO_MATRICULA) REFERENCES ALUNO (CODIGO_MATRICULA),
DATA_MATRICULA DATE NOT NULL,
REGISTRO_AUSENCIA VARCHAR(200) NOT NULL
);