CREATE DATABASE CHAVE_ESTRANGEIRA;

CREATE TABLE FUNCIONARIO(
MATRICULA INT(6) NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
ENDERECO VARCHAR(50) NOT NULL,
CARGO VARCHAR(20) NOT NULL
);

CREATE TABLE DEPENDENTE(
RG VARCHAR(12) NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
PARENTESCO VARCHAR(10) NOT NULL,
MATRICULA INT(6) NOT NULL,
FOREIGN KEY(MATRICULA) REFERENCES FUNCIONARIO (MATRICULA)
);

CREATE TABLE PESSOA(
ID INT(6) NOT NULL,
COD INT(6) NOT NULL,
NOME VARCHAR(255) NOT NULL,
SOBRENOME VARCHAR(255),
PRIMARY KEY(ID,COD)
);

CREATE TABLE DEPENFUN(
RG VARCHAR(12) NOT NULL,
MATRICULA INT(6) NOT NULL,
FOREIGN KEY(RG)REFERENCES DEPENDENTE(RG),
FOREIGN KEY(MATRICULA)REFERENCES FUNCIONARIO(MATRICULA),
PRIMARY KEY(RG, MATRICULA)
);