CREATE DATABASE BIBLIOTECA;

 CREATE TABLE LIVRO(
 CODIGO VARCHAR(20) PRIMARY KEY,
 NOME VARCHAR(20) NOT NULL,
 ANO YEAR NOT NULL
 );
 
 CREATE TABLE AUTOR(
 CPF INTEGER(20) PRIMARY KEY,
 NOME VARCHAR(20) NOT NULL,
 ENDEREÇO VARCHAR(50) NOT NULL,
 TELEFONE INTEGER(20) NOT NULL
 );
 
 CREATE TABLE EDIÇÃO(
 IBNS INTEGER(20) PRIMARY KEY,
 NUMERO_DE_PAGINAS INTEGER(5) NOT NULL,
 VALOR INTEGER(10) NOT NULL
 );
 
 CREATE TABLE EDITORA(
 CNPJ INTEGER(20) PRIMARY KEY,
 NOME VARCHAR(20) NOT NULL,
 ENDEREÇO VARCHAR(50) NOT NULL
 );